// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgrtfuekrgvxtswwnags.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZncnRmdWVrcmd2eHRzd3duYWdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjU3NTMsImV4cCI6MjA2NTYwMTc1M30.9hCGjmQc0eGSL_hFeYfQgzRdq3MVExMy8rEAHZd32Bc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);